# Generated by Django 5.2 on 2025-08-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
